version: "3.3"
services:
  web:
    environment: 
      - TZ=Asia/Kolkata
    build: 
      context: ./dashboard
      dockerfile: dev.dockerfile
      cache_from:
        - alpine:latest
    image: h20180061/dashboard:${TAG}
    ports:
      - "80:80"
    container_name: web
    depends_on:
      - app

  app:
    environment: 
      - TZ=Asia/Kolkata
    build: ./app
    image: h20180061/trends:${TAG}
    ports:
      - "5000:5000"
      - "123"
    container_name: app
    volumes:
      - appdata:/home/app/data
      

volumes:
  appdata:
    driver: local
    driver_opts:
      type: none
      device: /c/Users/vedvp/sasonline/app/data
      o: bind
